name: test_application
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons:
  flutter_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.14
  #flutter_lints: ^2.0.0


flutter:
  uses-material-design: true